### ISSUE TITLE
Pressing `esc` key won't close the modal if the `shouldCloseOnOverlayClick` is set to `false`

### ISSUE THREAD

**Issue by antonhalim** [reactjs/react-modal#186]
### Summary:

It potentially might be a bug or just a question, I have a modal that the `shouldCloseOnOverlayClick={false}`, obviously clicking on overlay will not close the modal, but pressing on an `esc` key after that will not close the modal as well. But, opening a modal and pressing the `esc` key alone without clicking on overlay will close the modal as expected.
### Steps to reproduce:
1. Creates a new `react-modal` component.
2. Set component option of `shouldCloseOnOverlayClick={false}`.
3.  Run server, open the modal, and clicking on the overlay layer.
4. Press the `esc` button.
### Expected behavior:

The modal should close.

**Comment by claydiffrient** [comment]
@antonhalim I'm sorry for the delay on this.  The reason this behaves this way is that the keydown handler is associated with the content of the modal rather than the overlay.  Thus if focus isn't on the content, then this handler doesn't fire.

I think we can rethink this, but probably not until version 2.  Moving it to the overlay instead seems to be a better option.  I'll put it on our roadmap for v2.
