### ISSUE TITLE
`setAppElement()` not working as documented

### ISSUE THREAD

**Issue by rogeriopvl** [reactjs/react-modal#221]
When using `.setAppElement('#some_node')` the modal element still gets appended to `document.body`.

I see that this functionality was removed in `v1.3.0` but the docs are still mentioning that it's available.

I was counting on this feature because my React app lives inside a backbone view, so I need to make sure that the modal element is appended to the app container and not `document.body` (which is outside the react app's boundaries).

Is there any chance to bring this back as an optional feature?

**Comment by claydiffrient** [comment]
@rogeriopvl I'm sorry you're experiencing problems.

What you want will likely come to be once #183 gets merged in.  That being said, the appElement isn't where it gets appended, it's the element that is aria hidden.  It's important that this happen so that when the modal is open everything behind it gets hidden from screenreaders.

You shouldn't have any problem appending the element outside of the React app boundary.  The modal uses a "portal" so you can render the modal and its contents outside of the normal boundaries of your react app.  The only really important things is that the modal gets rendered outside of the appElement so that it doesn't get hidden with all the rest.

Does that make sense?

**Comment by rogeriopvl** [comment]
Kind of. It's just that this change should have been a major bump (2.0.0) and not minor because it breaks expected behaviour.

**Comment by claydiffrient** [comment]
Apologies about that.  I guess that I didn't see it that way when I cut the release.  The change to make appending the element elsewhere should have never happened.  It was a mistake at the time because the solution that was committed broke accessibility.  Reverting back to the fully accessible behavior seemed to me to be more of a bugfix/minor change.  That being said I can totally see how it would have merited a major bump.

I also didn't realize that the docs still indicated that there was a way to change the anchor point from being `document.body`.  I've corrected that issue.

**Comment by claydiffrient** [comment]
I believe that all documentation is currently up to date with the current behavior.  I'm closing this issue for now.  If it turns out to be not the case, let's reopen it.
