### ISSUE TITLE
Bundling the entire React despite using a CDN

### ISSUE THREAD

**Issue by sandzone** [reactjs/react-modal#235]
I use a cdn for React. But, the entire React library is being bundled into my production file due to react modal. 

I use browserify and gulp to create the bundle. I also use react-slider.  I am not facing such an issue over there. 

Is there any dependency on a particular React version that is leading to this?  I am on React  v15.3.2

My gulpfile.js has the following config
browserify-shim {
"react":"global:React", 
"react-dom":"global:ReactDOM"
}

**Comment by claydiffrient** [comment]
As far as I can tell we have the package.json setup appropriately to make sure that `react` and `react-dom` are both external to the library.

I'm hoping that you've been able to figure this out by now.  Because I can't see anything we can do differently at this point, I'm going to close the issue.  If it turns out there is something that we can do, then I'd love to reopen it.
