### ISSUE TITLE
shouldCloseOnOverlayClick

### ISSUE THREAD

**Issue by sgentile** [reactjs/react-modal#305]
### Summary:
I have the shouldCloseOnOverlayClick set to true - yet it's not closing the overlay

```
<Modal
                    isOpen={this.state.show}
                    style={this.customStyles}
                    shouldCloseOnOverlayClick={true}
                    contentLabel="Modal">
...
```

**Comment by claydiffrient** [comment]
You need to have a `onRequestClose` prop on the modal. That will let the modal know what to do in order to close. Something as simple as `onRequestClose={() => this.setState({show: false})` should do it for you.

I'll make sure to note this down and make sure it's documented more clearly. We're changing things around the props for v2 see #282 for more details.
