### ISSUE TITLE
Reduce build size by swapping out lodash.assign for a minimal Object.assign

### ISSUE THREAD

**Issue by olov** [reactjs/react-modal#332]
I did a clone of the repo followed by `NODE_ENV=production scripts/build`, which produced a 16826 bytes react-modal.min.js (5358 bytes gzipped).

Replacing the lodash assign import in ModalPortal.js with a minimal Object.assign polyfill (I took the TS one just for example):
```
function assign(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
}
```

...produced a 14516 bytes react-modal.min.js (4418 bytes gzipped).

That's an 18% (gzipped size) reduction, which adds up on slow networks and devices.

**Comment by jdalton** [comment]
In this case since `lodash.assign` is being used you should totally replace it with [babel-plugin-transform-object-assign](https://www.npmjs.com/package/babel-plugin-transform-object-assign). In other cases when using Lodash and size is a concern you should check out [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin). It disables features sets and edge cases by default to reduce bundle sizes.
