### ISSUE TITLE
How to perform action on modal open?

### ISSUE THREAD

**Issue by AndrewRayCode** [reactjs/react-modal#50]
It seems that with the `isOpen` api, neither `componentDidMount` nor `componentDidUpdate` actually guarantee the modal is open, even when making sure props.isOpen is set. I'm not sure what causes the delay, but if I want to do something like focus an input on modal open, I can't do it because the modal isn't visible yet.

**Comment by yhjor1212** [comment]
set it 'true'

**Comment by DelvarWorld** [comment]
@yhjor1212 what? set what to true?

**Comment by anatoliyarkhipov** [comment]
What did you mean by "delay"? From what moment it is delayed?

**Comment by thesunny** [comment]
Thanks for putting this React Modal together. Really nice.

I think this and the issue on focus can be handled by having an onAfterOpen callback passed in as a prop. This way, after the modal is open, we can perform an action on open which includes the ability to set the focus.

My feeling is that it may be beneficial to remove the auto-focus since it's not necessary in a lot of cases and in cases where you want it, you can easily add focus through the onAfterOpen callback. In any case, if you do keep it, just a reminder to make sure the autofocus happens before the onAfterOpen callback or else any focus set in the callback would be lost.

Would also solve the following issue: https://github.com/rackt/react-modal/issues/51

**Comment by claydiffrient** [comment]
Closing because #154 was released.
