### ISSUE TITLE
How to make responsive overlay

### ISSUE THREAD

**Issue by devhyunjae** [reactjs/react-modal#671]
### Steps to reproduce:

 1. I want to make the overlay responsive like this. Code

```
const customStyles = {
  overlay: {
    backgroundColor: 'transparent',
    left: '320px',
    top: '77px',
    '@media (max-width: 900px)': {
      left: '0px',
      top: '110px',
      width: '100%',
      height: '100%'
    }
  }
};

<Modal
  style={ customStyles }  
>
  <h1>hello world</h1>
</Modal>
```

### Expected behavior:
Support media query or other responsive tools

**Comment by cmcaboy** [comment]
Did you find a solution to this? @devhyunjae

**Comment by julessaysrawr** [comment]
In case anyone else encounters this, this short answer is **you can't**.  It turns out that there are certain features of css that are not or can't be implemented in js.

[Stack overflow](https://stackoverflow.com/questions/28405444/inline-css-styles-in-react-how-to-implement-media-queries)

This also applies to :pseudo-elements like : hover, etc.

There are two options that I can see:

1) Use a css-in-js [library:](https://github.com/MicheleBertoli/css-in-js)

2) override the css
```
            <ReactModal
              isOpen={this.state.showModal}
              contentLabel="Success message"
              // style={{ width: '50%', height: '50%', backgroundColor: 'blue' }}
              style={{
                overlay: {
                  zIndex: '11'
                },
                content: {
                  width: '300px',
                  height: '200px',
                  margin: '15% auto',
                  padding: '0',
                  inset: '0'
                }
              }}
            >
```
```
.ReactModal__Content {
  @include respond(sm) {
    width: 100% !important;
    height: 100% !important;
    margin: 0 auto !important;
  }
}
```
