### ISSUE TITLE
Add custom html attributes to the portal div, overlay div and content div

### ISSUE THREAD

**Issue by joeswick999** [reactjs/react-modal#739]
### Summary:
Good morning,

We should be able to add custom html attributes to each part of the modal. I am currently in a situation where I need to add an html "id" to the portal element (div) so I can grab it and do something with it, but I have no way of doing it...

**Comment by baruchvlz** [comment]
This is a very specific use case and I think it will add more properties to a component that already has quite a few of them.

I think a better solution would be to pass the element reference after the dialog is open.

```typescript
onAfterOpen: (modalRef: RefObject<HTMLDivElement>) => void
```

**Comment by baruchvlz** [comment]
Changes are [here](https://github.com/baruchvlz/react-modal/commit/a4685617a56237e84fec94b828dd00ed357c4ad6). If the project managers are ok with this, I'll open the PR.

**Comment by diasbruno** [comment]
@baruchvlz Contributions are always welcome. 

There are a few changes I'm trying to add on version 4, like be able to use custom overlays and content. It seems the right way to go, because it would also help people that are using styled components.

Maybe, react-modal can work just like an "engine", if users want it to be more customizable and/or have more control over it.

Please, check out [react-modal v4](https://github.com/reactjs/react-modal/tree/v4) if you are interest in contribute.

**Comment by baruchvlz** [comment]
> Contributions are always welcome.

Added a PR for this issue.

> There are a few changes I'm trying to add on version 4, like be able to use custom overlays and content. It seems the right way to go, because it would also help people that are using styled components.

This makes sense more for content than for overlay, though it wouldn't hurt to have both. I'll take a look and see if there's anything I can help with.
