### ISSUE TITLE
Modal doesn't trap focus when re-entering document

### ISSUE THREAD

**Issue by danielnixon** [reactjs/react-modal#742]
### Summary:
react-modal doesn't trap focus when re-entering a document that contains an open modal.

### Steps to reproduce:

 1. Open a react-modal modal
 2. Move focus outside the document, for example by clicking the mouse in your browser's address bar or pressing ctrl+l
 3. Hit tab key a number of times until focus moves back into the document

### Expected behavior:
Focus is trapped inside the still-open modal when focus moves back into the document.

### Actual behavior:
Focus moves through the document behind the modal.

### Link to example of issue:
https://mgwy6v6e.codesandbox.io/

### Additional notes:
Compare this behaviour to https://davidtheclark.github.io/react-aria-modal/demo/ which doesn't have this issue.

**Comment by danielnixon** [comment]
See https://github.com/davidtheclark/focus-trap/blob/master/index.js#L219-L220

**Comment by jasonkiss** [comment]
Based on the account at https://developer.paciellogroup.com/blog/2018/06/the-current-state-of-modal-dialog-accessibility/, it could be that a combination of `aria-modal` on the modal (to take advantage of that attribute's current and future support in browsers) alongside a combination of `aria-hidden` and an `inert` polyfill on elements outside the modal (until `aria-modal` support is complete) might do the trick.

**Comment by holloway** [comment]
I'm happy to develop a PR for this providing the developers of React-Modal agree on a basic approach.

Tagging @diasbruno @claydiffrient @ryanflorence in this ticket from March.

In duplicate issue #787 I suggested this potential fix but of course I'm open to other suggestions... any ideas?

> While a modal is open we could temporarily insert some focusable elements as the first child and last child of `<body>` that immediately move focus to the modal content. I guess these could be just `<div tabindex="0"></div>` elements.
> 
> I'm not sure how this would work with nested modals. Perhaps we'd restore focus to the most recently opened modal.
> 
> I think this needs to be plain JS (not React) to ensure these <div tabindex="0" /> elements are the first and last in <body>, but obviously we'd use lifecycle methods to clean up if React Modal was unmounted.

We could use React Portals but then, I think, we'd need to make the container elements in plain JS so I don't think Portals would give us much.

**Comment by holloway** [comment]
One approach that I've discounted is: listening for keyboard events and testing whether `document.activeElement` is within the modal content, however screen readers access text nodes that aren't focusable so document.activeElement wouldn't indicate whether they were accessing content outside the modal.

**Comment by diasbruno** [comment]
I have one question: this issue can be cause by misplacing the `aria-hidden` attribute?

If I have something link this on my document:

```html
<div>
  <div id="app" aria-hidden="true"></div>
  <div id="modal"></div>
</div>
```

When the page becomes the active view, should the page restore its previous active element?

**Comment by jasonkiss** [comment]
`aria-hidden` only prevents the nodes being exposed in the a11y tree. So UI components are still there to receive user interaction via the Tab key, but nothing will be announced by screen readers when items receive focus. And for sighted users, they’ll be tabbing around in the page under the overlay, trying to figure out where they are/what is going on.
It’s not a screen reader bug or a browser bug, since the browser has not been programmatically told (e.g. via `inert` or possibly `tabindex="-1"`?) to prevent the items under the overlay from receiving keyboard focus when entering from the browser chrome  (as opposed to from within the modal where keyboard focus should otherwise already be constrained).

**Comment by holloway** [comment]
Yep, this bug is present when correctly setting `aria-hidden` and we can `<tab>` to the content under the modal.

`react-modal` should work on pages that are only partially React (ie, not just setting aria-hidden on a single app root), so the solution should trap focus on all `body.childNodes[]` except for the modal portal.

[`inert`](https://wicg.github.io/inert/explainer.html) would be a great fix, but browser support is poor, and I believe textNodes that are immediate children of `<body>` would need to be wrapped to set an `inert` attribute on them. This DOM mangling sounds like it would cause bugs.

`tabindex="-1"` would still mean textNodes preceding the element would be available to screen readers.

So overall I think the idea of inserting an element at the start and end of `<body>` to receive focus and move it to the modal is probably the most straight-forward solution.

**Comment by jasonkiss** [comment]
To clarify, `aria-hidden="true"` successfully prevents screen readers from reading the content set with that attribute, textNodes and otherwise. That bit works. 

It's the fact that, when coming in from the browser chrome, the Tab key will still set focus to focusable elements outside/under the modal (at least in Chrome, FF, and Safari—doesn't appear to happen in IE11 or EdgeHTML). But because that focusable content is set with or inherits `aria-hidden="true"` from an ancestor, it is not represented in the accessibility tree, and so screen readers won't announce the focused element's accessible name.

So `tabindex="-1"` on focusable elements outside/under the modal could still be a solution, if a bit clunky.

**Comment by holloway** [comment]
I've developed a wrapper around `react-modal` to prototype a fix, and this fix seems to trap focus correctly.

Usage is,

```javascript
import Modal from 'react-modal';
import ModalBody from 'react-modal-wrapper';

<ModalBody isOpen={isOpen}>
    <Modal isOpen={isOpen}>
        ...
    </Modal>
</ModalBody>
```

The prototype code is here: https://github.com/GOVTNZ/govtnz-design-system/blob/master/packages/react-modal-body/src/index.tsx

Obviously a fix that's included with `react-modal` would have different implementation details, but the approach of elements inserted at the start/end of `<body>` to move focus to the modal does work.

Specifically the implementation details of ensuring the trap elements stay at the start/end of `<body>` by checking 10 times a second, and selecting the Modal content with a selector, that should be changed in any PR.

Thoughts? 

(@diasbruno )

**Comment by holloway** [comment]
Sorry I'm not meaning to nag people about this but I'm keen to progress it. Is there anything I can do? Should I raise a PR with this approach?

**Comment by diasbruno** [comment]
@holloway You can open a PR and we can discusss the implementation details. It'll be better to see what is going to change.

**Comment by holloway** [comment]
@diasbruno done! see #791
