### ISSUE TITLE
Excessive amount of portals in dom

### ISSUE THREAD

**Issue by tomsonpl** [reactjs/react-modal#760]
### Summary: 
Hi, it's rather a question (not sure if an issue but wanted to bring your attention to this case), if portals should be created even when Modal has isOpen state set to false. We are having quite a big app with many items opening modals.  Version used is:  "react-modal": "3.6.1". Whenever we use modal and leave mounting / showing logic to be handled there - we end up with having an outrageous number of portals been created. 

<img width="220" alt="Zrzut ekranu 2019-06-17 o 11 45 26" src="https://user-images.githubusercontent.com/16632552/59595383-fb5bde80-90f5-11e9-9130-28f918eaa93a.png">

Is there a reason you create them on ''mount'' even though the  isOpen state is set to false?

I tried to handle this by doing conditional render on modal, but that is duplicating logic both in component and in modal. 

Thanks!

### Steps to reproduce:

 1.
 2.
 3.

### Expected behavior:
I Would expect React Modal Portal to be created on Modal's Open event.

**Comment by adambartniak** [comment]
Same here

**Comment by diasbruno** [comment]
Hi @tomsonpl @adambartniak, can you make a reproducible example, please?

**Comment by pixelplant** [comment]
@tomsonpl Seems that everytime you create a <Modal> tag it adds a portal class for it.
This is the code I used before that had lots of portal classes, like in your case
```
                    <Modal
                        className="crm-modal"
                        isOpen={this.modalIsOpen}
                        contentLabel="Example Modal"
                        onRequestClose={this.closeActivityModal}
                    >
                        <div>I am a modal</div>
                        <button onClick={this.closeActivityModal}>close</button>
                        <form>
                            <input/>
                        </form>
                    </Modal>
```
and here is the same code that I updated so that it only shows the modal if it's supposed to be open. This only generates 1 portal class for each open modal. I wonder if there's any downside to it though.
```
                {this.modalIsOpen ?
                    (<Modal
                        className="crm-modal"
                        isOpen={true}
                        contentLabel="Example Modal"
                        onRequestClose={this.closeActivityModal}
                    >
                        <div>I am a modal</div>
                        <button onClick={this.closeActivityModal}>close</button>
                        <form>
                            <input/>
                        </form>
                    </Modal>)
                    : null
                }
```

**Comment by tomsonpl** [comment]
@pixelplant this is exactly the case, and exactly how I tried to work around it. However it doesnt seem clear to have opening logic duplicated. ```                {this.modalIsOpen ? ``` and  ```                        isOpen={true}```  while we could have it in ```isOpen={this.modalIsOpen}``` only.

**Comment by universse** [comment]
> pen modal. I wonder if there's any downside to it though. The functionality seems to be the same.

Do you have transition for modals? Does it work as expected?

**Comment by tomsonpl** [comment]
@diasbruno  thanks, however this does not answer "WHY" ;p what is the upside of handling "OPEN state" inside modal,  against conditional rendering the whole modal in the first place.  It doesn't sound sane to render PORTAL x 50, when you can have just one.

**Comment by mchl-hub** [comment]
Hello, @diasbruno the question is whether it is possible to conditionally render `React.createPortal` for projects with React v16 or above. The condition would be modal open state.

I see the argument behind backward compatibility and code coherence, but, to begin with, do we really need to keep backward compatibility for React lower than v16, I suggest major version bump and provide the best experience for developers using current React major version. Of course only when we establish that this is possible as asked above.

Considering using modals in lists, it is always possible to use less modals, or move them up the component tree, but that binds users to specifically think about optimization solely because or `react-modal` package. Furthermore, it almost always increases code complexity, so not always a good solution.

My point is to present my own use case issue and to suggest possible solution, your decision though. I will use `react-modal` anyway, because it is a great work :) Thanks!

**Comment by VicFrolov** [comment]
Hello, @diasbruno just wanted to check in and see if this was anywhere in the pipeline, or if anything has changed between then and now. Thanks!

**Comment by diasbruno** [comment]
@VicFrolov No...sorry.

**Comment by zanderlan-n** [comment]
Hello @diasbruno any updates on this issue? 🤞

**Comment by diasbruno** [comment]
@zanderlan-n Are you adding a modal inside of a component that is created from a list?

**Comment by diasbruno** [comment]
This is not an issue. 

My 2 cents is that the application has a modal inside of a component that is rendered from a list.

It's the only case where this is possible (if you have this number of modal in your application, than the problem is the application :joy:).

So you have a problem of coupling vs cohesion. If you have this scenario, the solution is to move the modal outside of the component that goes in a loop.

**Comment by diasbruno** [comment]
Also, each modal creates its own node, because we can have nested modals.

**Comment by agjs** [comment]
Couldn't you just create an abstraction over the modal and return null if the modal isn't opened. E.g.

```js
import classNames from "classnames";
import ReactModal from "react-modal";

ReactModal.setAppElement("#root");

export const Modal = ({ children, isOpen, handleClose, className, style }) => {
  if (!isOpen) {
    return null;
  }

  return (
    <ReactModal
      isOpen={isOpen}
      onRequestClose={handleClose}
    >
      {children}
    </ReactModal>
  );
};
```

This way, you don't have to wrap your logic into those strange ternary operators. Cheers

**Comment by diasbruno** [comment]
@agjs This does the same thing we already do internally though. 
But...making the modal's children dynamic is the way to go.
But...having too many portal elements doesn't cause any problem.
